name: dart_spotify_api
description: A sample command-line application.
version: 1.1.0
repository: https://github.com/MusilyApp/dart_spotify_api

environment:
  sdk: ^3.4.4

dependencies:
  dio: ^5.6.0
  flutter_secure_storage: ^9.2.2
  oauth2_client: ^3.3.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
